#!/usr/bin/env bash
set -Eeuo pipefail
: "${FOSSBILLING_DIR:=/opt/lampp/htdocs}"
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
SOURCE_DIR="$SCRIPT_DIR/fossbilling/Serviceinterserver"
CUSTOMER_API_DIR="$SCRIPT_DIR/fossbilling/Cloudvps"
DOMAINS_SOURCE="$SCRIPT_DIR/fossbilling/Quizontaldomains"
THEME_OVERRIDES_DIR="$SCRIPT_DIR/fossbilling/theme-overrides"
[[ $EUID -eq 0 ]] || { echo 'Run with sudo -E.' >&2; exit 1; }
[[ -d "$SOURCE_DIR" ]] || { echo "Module source missing: $SOURCE_DIR" >&2; exit 1; }
MODULES_DIR=''
for candidate in "$FOSSBILLING_DIR/modules" "$FOSSBILLING_DIR/src/modules" "$FOSSBILLING_DIR/htdocs/modules"; do
  [[ -f "$candidate/Invoice/manifest.json" ]] && { MODULES_DIR=$candidate; break; }
done
[[ -n "$MODULES_DIR" ]] || { echo 'Could not locate the FOSSBilling modules directory.' >&2; exit 1; }
TARGET="$MODULES_DIR/Serviceinterserver"
WEB_USER=${FOSSBILLING_WEB_USER:-$(stat -c '%U' "$MODULES_DIR/Invoice")}
WEB_GROUP=${FOSSBILLING_WEB_GROUP:-$(stat -c '%G' "$MODULES_DIR/Invoice")}
install -d -m 0755 -o "$WEB_USER" -g "$WEB_GROUP" "$TARGET"
cp -a "$SOURCE_DIR"/. "$TARGET"/
chown -R "$WEB_USER:$WEB_GROUP" "$TARGET"
find "$TARGET" -type d -exec chmod 0755 {} +
find "$TARGET" -type f -exec chmod 0644 {} +
CUSTOMER_TARGET="$MODULES_DIR/Cloudvps"
install -d -m 0755 -o "$WEB_USER" -g "$WEB_GROUP" "$CUSTOMER_TARGET"
cp -a "$CUSTOMER_API_DIR"/. "$CUSTOMER_TARGET"/
chown -R "$WEB_USER:$WEB_GROUP" "$CUSTOMER_TARGET"
find "$CUSTOMER_TARGET" -type d -exec chmod 0755 {} +
find "$CUSTOMER_TARGET" -type f -exec chmod 0644 {} +
# Customer DNS record manager (theme probe stays silent while inactive).
if [[ -d "$DOMAINS_SOURCE" ]]; then
  DOMAINS_TARGET="$MODULES_DIR/Quizontaldomains"
  install -d -m 0755 -o "$WEB_USER" -g "$WEB_GROUP" "$DOMAINS_TARGET"
  cp -a "$DOMAINS_SOURCE"/. "$DOMAINS_TARGET"/
  chown -R "$WEB_USER:$WEB_GROUP" "$DOMAINS_TARGET"
  find "$DOMAINS_TARGET" -type d -exec chmod 0755 {} +
  find "$DOMAINS_TARGET" -type f -exec chmod 0644 {} +
fi
APP_ROOT=$(dirname "$MODULES_DIR")
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
# Storefront URL that the order page domain search card bounces to (/domains?q=…).
# Priority: STOREFRONT_URL env → APP_URL in the repo .env → empty (in-billing fallback).
STOREFRONT_URL=${STOREFRONT_URL:-}
if [[ -z "$STOREFRONT_URL" && -f "$REPO_ROOT/.env" ]]; then
  RAW_APP_URL=$(grep -m1 '^APP_URL=' "$REPO_ROOT/.env" | cut -d= -f2- || true)
  STOREFRONT_URL=$(printf '%s' "$RAW_APP_URL" | tr -d "\"' \t\r")
fi
STOREFRONT_URL=${STOREFRONT_URL%/}
# Theme overrides are CLIENT-area templates (huraga). The Twig override loader
# checks <theme>/html_custom for EVERY theme — including admin themes whose
# layout/templates share file names — so admin themes must never receive these.
ADMIN_THEMES=${FOSSBILLING_ADMIN_THEMES:-admin_default}
is_admin_theme() {
  local name
  name=$(basename "$1")
  case " $ADMIN_THEMES " in *" $name "*) return 0 ;; esac
  return 1
}
if [[ -d "$THEME_OVERRIDES_DIR" && -d "$APP_ROOT/themes" ]]; then
  for theme_dir in "$APP_ROOT/themes"/*; do
    [[ -d "$theme_dir/html" ]] || continue
    if is_admin_theme "$theme_dir"; then
      # Clean up overrides accidentally copied here by older installer versions.
      if [[ -d "$theme_dir/html_custom" ]]; then
        for override in "$THEME_OVERRIDES_DIR"/*.twig; do
          [[ -f "$override" ]] || continue
          rm -f "$theme_dir/html_custom/$(basename "$override")"
        done
        rmdir --ignore-fail-on-non-empty "$theme_dir/html_custom" 2>/dev/null || true
        echo "Cleaned client overrides out of admin theme: $(basename "$theme_dir")"
      fi
      continue
    fi
    install -d -m 0755 -o "$WEB_USER" -g "$WEB_GROUP" "$theme_dir/html_custom"
    for override in "$THEME_OVERRIDES_DIR"/*.twig; do
      [[ -f "$override" ]] || continue
      install -m 0644 -o "$WEB_USER" -g "$WEB_GROUP" "$override" "$theme_dir/html_custom/$(basename "$override")"
    done
    printf '{# Generated by deploy/install-interserver-provisioning.sh — do not edit on the server. #}\n{%% macro url() %%}%s{%% endmacro %%}\n' "$STOREFRONT_URL" \
      > "$theme_dir/html_custom/qc_storefront.html.twig"
    chown "$WEB_USER:$WEB_GROUP" "$theme_dir/html_custom/qc_storefront.html.twig"
  done
  echo "Storefront link for the order page: ${STOREFRONT_URL:-<fallback: in-billing domain form>}"
fi
REGISTRAR_ADAPTERS_DIR="$SCRIPT_DIR/fossbilling/registrar-adapters"
if [[ -d "$REGISTRAR_ADAPTERS_DIR" ]]; then
  ADAPTER_TARGET="$APP_ROOT/library/Registrar/Adapter"
  if [[ -d "$ADAPTER_TARGET" ]]; then
    for adapter in "$REGISTRAR_ADAPTERS_DIR"/*.php; do
      [[ -f "$adapter" ]] || continue
      install -m 0644 -o "$WEB_USER" -g "$WEB_GROUP" "$adapter" "$ADAPTER_TARGET/$(basename "$adapter")"
      echo "Installed domain registrar adapter: $(basename "$adapter")"
    done
  else
    echo "Registrar adapter directory not found ($ADAPTER_TARGET); skipping registrar adapters." >&2
  fi
fi

# Quizontal: brand-safe server manager overrides (sanitized user-facing errors)
SERVER_MANAGERS_DIR="$SCRIPT_DIR/fossbilling/server-managers"
if [[ -d "$SERVER_MANAGERS_DIR" ]]; then
  MANAGER_TARGET="$APP_ROOT/library/Server/Manager"
  if [[ -d "$MANAGER_TARGET" ]]; then
    for manager in "$SERVER_MANAGERS_DIR"/*.php; do
      [[ -f "$manager" ]] || continue
      install -m 0644 -o "$WEB_USER" -g "$WEB_GROUP" "$manager" "$MANAGER_TARGET/$(basename "$manager")"
      echo "Installed server manager override: $(basename "$manager")"
    done
  else
    echo "Server manager directory not found ($MANAGER_TARGET); skipping server managers." >&2
  fi
fi
[[ -d "$APP_ROOT/data/cache" ]] && find "$APP_ROOT/data/cache" -type f ! -name '.gitignore' -delete

# --- Quizontal site settings ------------------------------------------------
# 1) FOSSBilling's "strict" security mode sets session cookies SameSite=Strict,
#    which silently DROPS the customer's session every time they arrive at the
#    billing site by clicking a link on the marketing storefront. Relax it to
#    "lax" (top-level navigation keeps working) and give sessions a 24h
#    lifespan instead of the 2h default. One-time backup: config.php.quizontal-backup
CONFIG_FILE="$APP_ROOT/config.php"
if [[ -f "$CONFIG_FILE" ]] && command -v python3 >/dev/null 2>&1; then
  cp -n "$CONFIG_FILE" "$CONFIG_FILE.quizontal-backup" || true
  python3 - "$CONFIG_FILE" <<'PYEOF'
import re, sys
path = sys.argv[1]
src = open(path).read()
orig = src
if "'security'" in src or '"security"' in src:
    src = re.sub(r"(['\"]mode['\"]\s*=>\s*)['\"]strict['\"]", r"\1'lax'", src)
    def lifespan(match):
        return match.group(1) + str(max(int(match.group(2)), 86400))
    src = re.sub(r"(['\"]session_lifespan['\"]\s*=>\s*)(\d+)", lifespan, src, count=1)
    if "'perform_session_fingerprinting'" in src or '"perform_session_fingerprinting"' in src:
        src = re.sub(r"(['\"]perform_session_fingerprinting['\"]\s*=>\s*)true", r"\1false", src)
    else:
        # Toggle absent — add it right after the security section opener (handles both [] and array() styles).
        src = re.sub(r"(['\"]security['\"]\s*=>\s*(?:array\s*\(|\[))",
                     r"\1\n        'perform_session_fingerprinting' => false,", src, count=1)
else:
    block = "    'security' => ['mode' => 'lax', 'session_lifespan' => 86400, 'perform_session_fingerprinting' => false],\n"
    src = re.sub(r"return\s*\[", "return [\n" + block, src, count=1)
if src != orig:
    open(path, 'w').write(src)
mode = re.search(r"['\"]mode['\"]\s*=>\s*['\"]([^'\"]+)['\"]", src)
span = re.search(r"['\"]session_lifespan['\"]\s*=>\s*(\d+)", src)
fp = re.search(r"['\"]perform_session_fingerprinting['\"]\s*=>\s*(true|false)", src)
print("config.php: security.mode=%s, session_lifespan=%s, fingerprinting=%s%s" % (
    mode.group(1) if mode else "MISSING",
    span.group(1) if span else "MISSING",
    ("OFF (good for mobile customers)" if fp and fp.group(1) == "false" else (fp.group(1).upper() + " (should be off)")) if fp else "MISSING",
    "" if src == orig else " (updated)"))
PYEOF
else
  echo "NOTE: could not adjust $CONFIG_FILE automatically - set 'security.mode' to 'lax' there manually."
fi

# 2) Professional store URLs: /hosting/vps and /hosting/domains (aliases for
#    the Custom Pages routes). The rewrite passes the target via ?_url= because
#    FOSSBilling's front controller prioritises $_GET['_url'] over REQUEST_URI
#    (per-directory rewrites do not always update REQUEST_URI reliably).
HTACCESS_FILE="$APP_ROOT/.htaccess"
if [[ -f "$HTACCESS_FILE" ]] && command -v python3 >/dev/null 2>&1; then
  python3 - "$HTACCESS_FILE" <<'PYEOF'
import re, sys
path = sys.argv[1]
src = open(path).read()
block = ("    # BEGIN Quizontal routes\n"
         "    # Pretty store URLs served by the Custom Pages module.\n"
         "    RewriteRule ^hosting/(vps|domains)/?$ index.php?_url=/custompages/$1 [L,QSA]\n"
         "    # END Quizontal routes\n")
existing = re.compile(r"\n? *# BEGIN Quizontal routes.*?# END Quizontal routes\n", re.S)
if re.search(existing, src):
    src = re.sub(existing, "\n" + block, src, count=1)
    open(path, 'w').write(src)
    print(".htaccess: store URL aliases updated")
else:
    anchor = "# Rewrite non-existent file/directory names to index.php."
    if anchor in src:
        open(path, 'w').write(src.replace(anchor, block + "\n    " + anchor.lstrip(), 1))
        print(".htaccess: /hosting/... store URL aliases installed")
    else:
        print(".htaccess: layout anchor not found - add the /hosting/ rewrite manually")
PYEOF
fi

# 3) XAMPP's php.ini garbage-collects PHP sessions after 24 idle minutes by
#    default, which logs customers out mid-shopping. Raise it to 24h.
PHPINI_FILE="${FOSSBILLING_PHP_INI:-$(dirname "$FOSSBILLING_DIR")/etc/php.ini}"
if [[ -f "$PHPINI_FILE" ]]; then
  if grep -q '^session.gc_maxlifetime' "$PHPINI_FILE"; then
    cur=$(sed -n 's/^session.gc_maxlifetime *= *//p' "$PHPINI_FILE" | head -n1 | tr -d ' ')
    if [[ "$cur" =~ ^[0-9]+$ ]] && (( cur < 86400 )); then
      sed -i 's/^session.gc_maxlifetime *=.*/session.gc_maxlifetime = 86400/' "$PHPINI_FILE"
    fi
  fi
  if grep -q '^session.cookie_samesite' "$PHPINI_FILE"; then
    sed -i 's/^session.cookie_samesite *=.*/session.cookie_samesite = Lax/' "$PHPINI_FILE"
  else
    printf '\nsession.cookie_samesite = Lax\n' >> "$PHPINI_FILE"
  fi
  echo "php.ini: gc_maxlifetime>=86400, cookie_samesite=Lax (restart Apache once: sudo /opt/lampp/lampp restart)"
fi


echo "Quizontal Cloud provisioning modules installed successfully."
echo 'Next: run bash deploy/activate-interserver-provisioning.sh from the repository.'
